export const CERTIFICATES_DATA = [
    {
        id: 1,
        slug: "python-ibm-certificate",
        title: "Python for Data Science, AI & Development",
        issuer: "IBM / Coursera",
        category: "programming",
        badgeClass: "badge-lightgreen",
        year: "2024",
        credentialId: "IBM-PY-DATA-AI",
        description: "Comprehensive certification verifying mastery of Python programming fundamentals, data structures, APIs, working with data, and basic library frameworks.",
        img: "/certificates/python-ibm-certificate-BUCfCAzv.png",
        skills: ["Python Programming", "APIs & Web Scraping", "Data Structures", "Pandas & NumPy", "JSON Handling", "Object Oriented Design"],
        url: "https://courses.cognitiveclass.ai/certificates/25de16cc7df74b1db5483bf6b02daf99"
    },
    {
        id: 2,
        slug: "gemini-certified-student",
        title: "Gemini Certified Student Ambassador",
        issuer: "Google / Gemini Lab",
        category: "generative AI",
        badgeClass: "badge-pink",
        year: "2024",
        credentialId: "GEM-STUDENT-AMB",
        description: "Earned designation verifying competency in using Google Gemini and Vertex AI suite for advanced content generation, prompt design, and agentic workflows.",
        img: "/certificates/gemini-certified-student-VSFRbvIU.png",
        skills: ["Google Gemini Suite", "Vertex AI Platform", "Generative Models", "AI Agent Workflows", "Prompt Optimization"],
        url: "https://edu.exceedlms.com/student/award/WB11vJM7oxfcQgqY4UGzDRAb"
    },
    {
        id: 3,
        slug: "deloitte-certificate",
        title: "Deloitte Tech Consulting Virtual Internship",
        issuer: "Deloitte / Forage",
        category: "consulting",
        badgeClass: "badge-lightblue",
        year: "2024",
        credentialId: "b7AdMjGfQuLBLHhG8",
        description: "Completed a simulation of a technology consulting project at Deloitte, specializing in cloud migration strategies, systems analysis, and data architecture proposal.",
        img: "/certificates/deloitte-certificate-BYsVzEjk.png",
        skills: ["Cloud Migration", "Systems Analysis", "Enterprise Tech", "Client Proposals", "Architecture Design"],
        url: "https://www.theforage.com/completion-certificates/9PBTqmSxAf6zZTseP/io9DzWKe3PTsiS6GG_9PBTqmSxAf6zZTseP_Mmn5KEnmePiLXkbLA_1750956563826_completion_certificate.pdf"
    },
    {
        id: 4,
        slug: "prompt-engineering-certificate",
        title: "Generative AI: Prompt Engineering Basics",
        issuer: "IBM / Coursera",
        category: "generative AI",
        badgeClass: "badge-orange",
        year: "2024",
        credentialId: "IBM-GEN-AI-PROM",
        description: "Credential validating skills in structuring prompts for Large Language Models (LLMs), prompt templates, context management, and avoiding AI hallucinations.",
        img: "/certificates/prompt-engineering-certificate-CdtYDgP4.jpg",
        skills: ["Prompt Engineering", "Large Language Models", "Context Ingestion", "AI Hallucination Mitigation", "Few-Shot Prompting"],
        url: "https://drive.google.com/file/d/16-6ryqgsBiH5hs4umf4QBpnfwyaI6mWf/view?usp=sharing"
    },
    {
        id: 5,
        slug: "nptel-certificate",
        title: "NPTEL National Programme on Technology Enhanced Learning",
        issuer: "IIT / NPTEL",
        category: "computer science",
        badgeClass: "badge-maroon",
        year: "2024",
        credentialId: "NPTEL-IIT-CS-98",
        description: "Academic certification validating comprehensive knowledge in algorithms, database design, software engineering, and core computing concepts.",
        img: "/certificates/nptel-certificate-BKFyWzAH.png",
        skills: ["Algorithms & Structures", "Database Management", "Software Architecture", "Operating Systems", "Systems Engineering"],
        url: "https://archive.nptel.ac.in/content/noc/NOC25/SEM1/Ecertificates/106/noc25-cs15/Course/NPTEL25CS15S75970098804268421.pdf"
    },
    {
        id: 6,
        slug: "hp-life-certificate",
        title: "HP LIFE Entrepreneurship & Business Communications",
        issuer: "HP Foundation",
        category: "business",
        badgeClass: "badge-lightblue",
        year: "2024",
        credentialId: "HPL-BIZ-COMM-24",
        description: "Validated mastery of business communications, financial modeling for small enterprises, customer relationship management, and digital marketing strategies.",
        img: "/certificates/hp-life-certificate-BNuGqLwT.png",
        skills: ["Business Communications", "Financial Modeling", "CRM Systems", "Digital Marketing", "Entrepreneurship Concepts"],
        url: "https://www.life-global.org/certificate/b57ae1f5-4f7c-411d-b78e-ef0f39486a4d"
    },
    {
        id: 7,
        slug: "tata-data-visualization",
        title: "Tata Data Visualization Virtual Experience",
        issuer: "Tata Group / Forage",
        category: "data science",
        badgeClass: "badge-lightgreen",
        year: "2024",
        credentialId: "TATA-DV-VINT",
        description: "Completed data visualization and analytics simulation for Tata Insights & Trust, focusing on formulating business questions, preparing clean visualizations, and presenting actionable insights.",
        img: "/certificates/tata-certificate.png",
        skills: ["Data Visualization", "Business Intelligence", "Dashboard Analytics", "Insight Delivery", "Data Storytelling"],
        url: "https://www.theforage.com/completion-certificates/ifobHAoMjQs9s6bKS/MyXvBcppsW2FkNYCX_ifobHAoMjQs9s6bKS_Mmn5KEnmePiLXkbLA_1756964336106_completion_certificate.pdf"
    },
    {
        id: 8,
        slug: "ux-figma-design-specialization",
        title: "UX/UI Design Specialization with Figma",
        issuer: "Coursera / UX Academy",
        category: "ui/ux design",
        badgeClass: "badge-pink",
        year: "2024",
        credentialId: "UX-FIGMA-SPEC-24",
        description: "Professional design credential validating expertise in user research, wireframing, high-fidelity prototyping, design systems, and visual design patterns using Figma.",
        img: "/certificates/ux-figma-certificate.jpg",
        skills: ["Figma Design Tool", "Prototyping & Wireframing", "User Research & Testing", "Visual Design Systems", "Responsive Web UI"],
        url: "https://drive.google.com/file/d/1CK75koVW12CnE5Yv8lcKpIfS820SnzgN/view?usp=sharing"
    },
    {
        id: 9,
        slug: "foundational-software-engineering-certificate",
        title: "Foundational Software Engineering Certificate",
        issuer: "HackerRank / SkillUp",
        category: "software engineering",
        badgeClass: "badge-pink",
        year: "2024",
        credentialId: "HR-SWE-FOUND-24",
        description: "Verified competency in software design patterns, modular code structure, algorithms complexity, data modeling, and testing best practices.",
        img: "/certificates/cartificat-CFGjbmET.png",
        skills: ["Design Patterns", "Modular Coding", "Algorithms Complexity", "Data Modeling", "Unit Testing", "System Design Basics"],
        url: "https://hackerrank.com"
    }
];
